### ISSUE TITLE
[Bug]: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by rony-ferzli** [eclipse-velocitas/vehicle-model-generator#33] opened 2023-02-09 05:56 UTC
### What happened?

when following instructions getting error
Exception has occurred: TypeError
'type' object is not subscriptable
  File "/home/vicente/vss/gen/vehicle-model-generator/sdv/model_generator/cpp/cpp_generator.py", line 83, in VehicleModelCppGenerator
    def __get_namespace_for_node(self, node: VSSNode) -> list[str]:
  File "/home/vicente/vss/gen/vehicle-model-generator/sdv/model_generator/cpp/cpp_generator.py", line 29, in <module>
    class VehicleModelCppGenerator:
  File "/home/vicente/vss/gen/vehicle-model-generator/sdv/model_generator/main.py", line 25, in <module>
    from sdv.model_generator.cpp.cpp_generator import VehicleModelCppGenerator
  File "/home/vicente/vss/gen/vehicle-model-generator/gen_vehicle_model.py", line 17, in <module>
    from sdv.model_generator.main import main
TypeError: 'type' object is not subscriptable

### Operating System

Linux

### What release version or branch did you use?

latest

### Relevant log output

```shell
see above
```

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by doosuu** [comment] 2023-02-13 07:14
@rony-ferzli  Can you please provide the exact input you have provided to the model generated to cause this issue? Thanks!

**Comment by BjoernAtBosch** [comment] 2023-02-15 08:45
@rony-ferzli Bug potentially fixed with release v0.3.0. Please check. Thx!

**Comment by rony-ferzli** [comment] 2023-02-26 19:12
great thank you!

**Comment by BjoernAtBosch** [comment] 2023-03-27 14:31
We are closing this issue as
* we were not able to reproduce it,
* the referenced code part has been reworked inbetween, and
* we did not receive further input/feedback for four weeks.

Please re-open if you have new insights. Thx!

**Closed as completed by BjoernAtBosch** 2023-03-27 14:31 UTC
Labels: bug

**Comment by rony-ferzli** [comment] 2023-03-27 14:33
Hi,

Yes please do, I did have the chance to verify but will check

Thank you!

Regards
Rony
